[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[context.production.environment]
  NEXT_PUBLIC_ENV = "production"

[context.deploy-preview.environment]
  NEXT_PUBLIC_ENV = "preview"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
